# syntax=docker/dockerfile:1
ARG TARGETPLATFORM
FROM --platform=$TARGETPLATFORM node:18-bullseye

WORKDIR /app

# deps
COPY web/package*.json ./
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

# project files
COPY web/vite.config.ts ./
COPY web/tsconfig.json ./
COPY web/index.html ./index.html
COPY web/public ./public
COPY web/src ./src

ARG MODE=wasm
ENV MODE=$MODE
# build
RUN npm run build

# serve
COPY web/server.js ./
EXPOSE 3000
CMD ["node","server.js"]
