# syntax=docker/dockerfile:1
ARG TARGETPLATFORM
FROM --platform=$TARGETPLATFORM node:18-bullseye AS build
WORKDIR /app
COPY web/package*.json ./
RUN npm ci
COPY web/ ./
RUN npm run build

FROM --platform=$TARGETPLATFORM node:18-alpine
WORKDIR /app
COPY web/package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/dist ./dist
COPY web/server.js ./server.js
COPY web/public ./public
EXPOSE 3000
CMD ["node", "server.js"]
