# syntax=docker/dockerfile:1
ARG TARGETPLATFORM
FROM --platform=$TARGETPLATFORM node:18-bullseye AS build
WORKDIR /app
COPY web/package*.json ./
RUN npm ci
COPY web/ ./
RUN npm run build

FROM --platform=$TARGETPLATFORM node:18-alpine
WORKDIR /app
RUN npm install -g http-server
COPY --from=build /app/dist ./dist
EXPOSE 3000
CMD ["http-server", "dist", "-p", "3000", "-a", "0.0.0.0"]
