version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - appnet
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:8000"
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
